# Require HDF5 via vcpkg CONFIG (no fallback)
find_package(hdf5 CONFIG REQUIRED)
set(HDF5_LIBRARIES)
foreach(_cand hdf5::hdf5-static hdf5::hdf5-shared hdf5::hdf5)
    if(TARGET ${_cand})
        list(APPEND HDF5_LIBRARIES ${_cand})
        break()
    endif()
endforeach()
foreach(_cand hdf5::hdf5_hl-static hdf5::hdf5_hl-shared hdf5::hdf5_hl)
    if(TARGET ${_cand})
        list(APPEND HDF5_LIBRARIES ${_cand})
        break()
    endif()
endforeach()
if(NOT HDF5_LIBRARIES)
    message(FATAL_ERROR "HDF5 CONFIG found but no usable targets (hdf5::hdf5[-static], hdf5::hdf5_hl[-static]) exposed")
endif()
message(STATUS "✓ Found HDF5 via CONFIG: ${HDF5_LIBRARIES}")

# Find FFTW3 (for OpenMP backend)
if(USE_OPENMP)
    # Require FFTW3f via vcpkg CONFIG (no fallback)
    find_package(FFTW3f CONFIG REQUIRED)
    set(FFTW_FOUND TRUE)
    set(FFTW_LIBRARIES FFTW3::fftw3f)
    # Some triplets export threads target under FFTW3::fftw3f_threads, others under FFTW3f::fftw3f_threads
    if(TARGET FFTW3::fftw3f_threads)
        list(APPEND FFTW_LIBRARIES FFTW3::fftw3f_threads)
    elseif(TARGET FFTW3f::fftw3f_threads)
        list(APPEND FFTW_LIBRARIES FFTW3f::fftw3f_threads)
    endif()
    message(STATUS "✓ Found FFTW3f via CONFIG: ${FFTW_LIBRARIES}")
endif()

# Find CUDA (for CUDA backend)
if(USE_CUDA)
    find_package(CUDAToolkit QUIET)
    if(NOT CUDAToolkit_FOUND)
        message(WARNING "CUDA Toolkit not found - CUDA backend will be disabled")
        message(WARNING "Please install CUDA Toolkit to enable CUDA backend (see DEPENDENCIES.md)")
        set(USE_CUDA OFF CACHE BOOL "" FORCE)
    else()
        message(STATUS "✓ Found CUDA Toolkit ${CUDAToolkit_VERSION}")
        # Set CUDA architectures - support from Kepler to Hopper
        set(CMAKE_CUDA_ARCHITECTURES 50 52 53 60 61 62 70 72 75 80 87 89 90 90a)
        message(STATUS "  - CUDA architectures: ${CMAKE_CUDA_ARCHITECTURES}")
    endif()
endif()

# Find OpenMP
if(USE_OPENMP)
    find_package(OpenMP QUIET)
    add_library(kspace_openmp_flags INTERFACE)

    if(OpenMP_FOUND)
        target_link_libraries(kspace_openmp_flags INTERFACE OpenMP::OpenMP_CXX)
        message(STATUS "✓ Found OpenMP ${OpenMP_CXX_VERSION}")
    else()
        if(APPLE)
            # On macOS, try to find Homebrew's libomp
            find_program(BREW_CMD brew)
            if(BREW_CMD)
                execute_process(
                    COMMAND ${BREW_CMD} --prefix libomp
                    OUTPUT_VARIABLE LIBOMP_PREFIX
                    OUTPUT_STRIP_TRAILING_WHITESPACE
                )
                if(LIBOMP_PREFIX)
                    target_compile_options(kspace_openmp_flags INTERFACE -Xclang -fopenmp)
                    target_link_libraries(kspace_openmp_flags INTERFACE -lomp)
                    target_include_directories(kspace_openmp_flags INTERFACE "${LIBOMP_PREFIX}/include")
                    target_link_directories(kspace_openmp_flags INTERFACE "${LIBOMP_PREFIX}/lib")
                    message(STATUS "✓ Using Homebrew's libomp from ${LIBOMP_PREFIX}")
                else()
                    message(WARNING "OpenMP not found. Please install libomp via Homebrew (see DEPENDENCIES.md)")
                endif()
            endif()
        else()
            # Try to enable OpenMP with -fopenmp for other compilers
            target_compile_options(kspace_openmp_flags INTERFACE -fopenmp)
            target_link_libraries(kspace_openmp_flags INTERFACE -fopenmp)
            message(STATUS "✓ Using compiler's OpenMP support")
        endif()
    endif()
endif()